on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build on esp-idf (latest)
      uses: espressif/esp-idf-ci-action@v1
      with:
        command: idf.py fullclean || idf.py build
        esp_idf_version: latest
        target: esp32s3

    - name: Build on esp-idf (v5.4)
      uses: espressif/esp-idf-ci-action@v1
      with:
        command: idf.py fullclean || idf.py build
        esp_idf_version: v5.4
        target: esp32s3

    - name: Build on esp-idf (v5.3)
      uses: espressif/esp-idf-ci-action@v1
      with:
        command: idf.py fullclean || idf.py build
        esp_idf_version: v5.3
        target: esp32s3
